### ISSUE TITLE
Parallel tests hang on python 3.7 & 3.8

### ISSUE THREAD

**Issue by justinlaughlin** [mfem/PyMFEM#230] opened 2024-07-02 01:30 UTC
For some reason, python `3.7` hangs when running `ex3p.py`, and python `3.8` hangs when running `ex0p.py`

`3.7`: https://github.com/mfem/PyMFEM/actions/runs/9752638384/job/26916499436
`3.8`: https://github.com/mfem/PyMFEM/actions/runs/9752638384/job/26916500077

All other tested versions of python (3.9, 3.10, 3.11) seem to be building and running all tests fine (although some tests like `ex18` are currently failing, all the tests run)

**Comment by sshiraiwa** [comment] 2024-08-06 17:41
@justinlaughlin I am not sure what is going on, since this error does not reproduce in my local environment.
Since Python3.7 passed EOL, and Python3.8 EOL is this October. We could skip these test? What do you think?

**Comment by justinlaughlin** [comment] 2024-08-06 18:19
I think we have a lot of combinations of possibilities to test for in PyMFEM and am fully in favor of simplifying (e.g. removing EOL/deprecated options).

**Comment by sshiraiwa** [comment] 2024-08-06 23:41
Okay. Closing this one.

**Closed by sshiraiwa** 2024-08-06 23:41 UTC
Labels: minor
